### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 15170016** [hedw1q/schedule#1]
BRO, the code is Good. But there's problem - where "перевод размеров обуви " table? I POCHEMU ON DOESN'T LIKE CALCULATOR?

**Comment by hedw1q** [comment]
> BRO, the code is Good. But there's problem - where "перевод размеров обуви " table? I POCHEMU ON DOESN'T LIKE CALCULATOR?

@15170016  VSE DOBAVILI, OSTALOS' ADD SOME FUNCTIONALITY
![2021-05-03_190215](https://user-images.githubusercontent.com/69858971/116901235-57747100-ac42-11eb-9021-1d8b5195a3f7.png)
